package com.jc.oa.product.domain;

import com.jc.foundation.domain.BaseBean;
/**
 * @author mrb
 * @version IDC业务表
*/
public class ToaProductIdc extends BaseBean {
	
	private static final long serialVersionUID = 1L;
	private Integer customersId;//   客户编码	private String customersName;//   公司名称	private String phone;//   联系电话	private String linkman;//   联系人	private String address;//   公司地址	private String taxid;//   所属行业	private String expandPeople;//   拓展经理	private String vask;//   客维经理	private String supporter;//   支持人员	private String cooperateType;//   合作状态	private String businessType;//   业务类型	private String machine;//   机房	private String equipment;//   机柜	private String bandwidth;//   带宽	private String port;//   端口	private String ipAddress;//   IP	private String remark;//   备注	public Integer getCustomersId() {	    return customersId;	}	public void setCustomersId(Integer customersId) {	    this.customersId=customersId;	}	public String getCustomersName() {	    return customersName;	}	public void setCustomersName(String customersName) {	    this.customersName=customersName;	}	public String getPhone() {	    return phone;	}	public void setPhone(String phone) {	    this.phone=phone;	}	public String getLinkman() {	    return linkman;	}	public void setLinkman(String linkman) {	    this.linkman=linkman;	}	public String getAddress() {	    return address;	}	public void setAddress(String address) {	    this.address=address;	}	public String getTaxid() {	    return taxid;	}	public void setTaxid(String taxid) {	    this.taxid=taxid;	}	public String getExpandPeople() {	    return expandPeople;	}	public void setExpandPeople(String expandPeople) {	    this.expandPeople=expandPeople;	}	public String getVask() {	    return vask;	}	public void setVask(String vask) {	    this.vask=vask;	}	public String getSupporter() {	    return supporter;	}	public void setSupporter(String supporter) {	    this.supporter=supporter;	}	public String getCooperateType() {	    return cooperateType;	}	public void setCooperateType(String cooperateType) {	    this.cooperateType=cooperateType;	}	public String getBusinessType() {	    return businessType;	}	public void setBusinessType(String businessType) {	    this.businessType=businessType;	}	public String getMachine() {	    return machine;	}	public void setMachine(String machine) {	    this.machine=machine;	}	public String getEquipment() {	    return equipment;	}	public void setEquipment(String equipment) {	    this.equipment=equipment;	}	public String getBandwidth() {	    return bandwidth;	}	public void setBandwidth(String bandwidth) {	    this.bandwidth=bandwidth;	}	public String getPort() {	    return port;	}	public void setPort(String port) {	    this.port=port;	}	public String getIpAddress() {	    return ipAddress;	}	public void setIpAddress(String ipAddress) {	    this.ipAddress=ipAddress;	}	public String getRemark() {	    return remark;	}	public void setRemark(String remark) {	    this.remark=remark;	}}

