<%@ page language="java" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/web/include/taglib.jsp"%>
<section class="scrollable  jcGOA-section" id="scrollable"> 
	<section class="panel clearfix" >
				<table class="table table-td-striped">
					<tbody>
						<tr>
							<td>客户名称</td>
							<td>
								${customer.companyName}
							</td>
							<td>客户类型</td>
							<td>
								${customer.memberType}
							</td>
							<td>业务类型</td>
							<td>
								${customer.serviceTypeValue}
							</td>
						</tr>
						<tr>
							<td>所属行业</td>
							<td>
								${customer.trade}
							</td>
							<td>所属机房</td>
							<td>
								${customer.machineValue}
							</td>
							<td>关联客户名称</td>
							<td>
								${customer.linkUser}
							</td>
						</tr>
						<tr>
							<td>签约拓展组</td>
							<td>
								${customer.department}
							</td>
							<td>拓展专员</td>
							<td>
								${customer.sale}
							</td>
							<td>维护专员</td>
							<td>
								${customer.tradeUser}
							</td>
						</tr>
						<shiro:hasPermission name="customer">
						<tr>
							<td>通信地址</td>
							<td>
								${customer.address}
							</td>
							<td>注册地址</td>
							<td>
								${customer.newAddress}
							</td>
							<td>纳税识别号</td>
							<td>
								${customer.taxid}
							</td>
						</tr>
						<tr>
							<td>开户银行</td>
							<td>
								${customer.bankName}
							</td>
							<td>银行帐号</td>
							<td>
								${customer.bankNo}
							</td>
							<td>发票类型</td>
							<td>
								${customer.ticketFlag}
							</td>
						</tr>
						<tr>
							<td>超流量取值方式</td>
							<td>
								${customer.overflowCategory}
							</td>
							<td>是否有代理费</td>
							<td>
								${customer.isDaili}
							</td>
							<td>代理费收款方</td>
							<td>
								${customer.dailiName}
							</td>
						</tr>
						<tr>
							<td>客户联系方式</td>
							<td>
								${customer.extStr2}
							</td>
							<td>客户接入商</td>
							<td>
								${customer.customerAccess}
							</td>
							<td>客户官网</td>
							<td>
								${customer.customerWebsite}
							</td>
						</tr>
						<tr>
							<td>公共号</td>
							<td>
								${customer.commonNumber}
							</td>
							<td>放置在公司业务</td>
							<td>
								${customer.companyPlaced}
							</td>
							<td>客户公司确定采购资源部门</td>
							<td>
								${customer.companyPurchasing}
							</td>
						</tr>
						</shiro:hasPermission>
						<!-- <tr>
							<td>首次入网时间</td>
							<td>
								<input type="text"  style="width:100%;"id="startIntel" name="startIntel" />
							</td>
							<td>终止时间</td>
							<td>
								<input type="text"  style="width:100%;"id="endIntel" name="endIntel" />
							</td>
							<td>客户评级</td>
							<td>
								<input type="text"  style="width:100%;"id="rating" name="rating" />
							</td>
						</tr> -->
					</tbody>
					</table>
			</section>
		</section>
<%@ include file="/WEB-INF/web/include/foot.jsp"%>