package com.jc.oa.contract.domain;

import com.jc.foundation.domain.BaseBean;
import java.util.Date;
/**
 * @author mrb
 * @version 付款方合同
*/
public class ToaContractOutcontract extends BaseBean {
	
	private static final long serialVersionUID = 1L;
	private String companyName;//   甲方公司名称	private String customer;//   乙方公司名称	private String contractNumber;//   合同编码	private String leard;//   发起人	private Date leardDate;//   发起日期	private String agreement;//   合同类型	private String contractStatus;//   合同类别	private String contractMoney;//   合同金额	private String seal;//   盖章	private Date place;//   归档时间	private Date startDate;//   合同起始日期	private Date endDate;//   合同终止日期	private String resource;//   合同资源	private String contractFile;//   合同扫描件	private String remark;//   备注	public String getCompanyName() {	    return companyName;	}	public void setCompanyName(String companyName) {	    this.companyName=companyName;	}	public String getCustomer() {	    return customer;	}	public void setCustomer(String customer) {	    this.customer=customer;	}	public String getContractNumber() {	    return contractNumber;	}	public void setContractNumber(String contractNumber) {	    this.contractNumber=contractNumber;	}	public String getLeard() {	    return leard;	}	public void setLeard(String leard) {	    this.leard=leard;	}	public Date getLeardDate() {	    return leardDate;	}	public void setLeardDate(Date leardDate) {	    this.leardDate=leardDate;	}	public String getAgreement() {	    return agreement;	}	public void setAgreement(String agreement) {	    this.agreement=agreement;	}	public String getContractStatus() {	    return contractStatus;	}	public void setContractStatus(String contractStatus) {	    this.contractStatus=contractStatus;	}	public String getContractMoney() {	    return contractMoney;	}	public void setContractMoney(String contractMoney) {	    this.contractMoney=contractMoney;	}	public String getSeal() {	    return seal;	}	public void setSeal(String seal) {	    this.seal=seal;	}	public Date getPlace() {	    return place;	}	public void setPlace(Date place) {	    this.place=place;	}	public Date getStartDate() {	    return startDate;	}	public void setStartDate(Date startDate) {	    this.startDate=startDate;	}	public Date getEndDate() {	    return endDate;	}	public void setEndDate(Date endDate) {	    this.endDate=endDate;	}	public String getResource() {	    return resource;	}	public void setResource(String resource) {	    this.resource=resource;	}	public String getContractFile() {	    return contractFile;	}	public void setContractFile(String contractFile) {	    this.contractFile=contractFile;	}	public String getRemark() {	    return remark;	}	public void setRemark(String remark) {	    this.remark=remark;	}	
}

